# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Steve
tagline:          'Steve Marshall'
description:      'The adventures of a fantastically inept programmer called Steve'
url:              http://stevemarshall.io
baseurl:          /

author:
  name:           'Steve Marshall'
  url:            https://twitter.com/SMdotIO

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

